### ISSUE TITLE
Allow for bulk notification config

### ISSUE THREAD

**Issue by seancdavis** [digerata/notify#16]
In working through real-world examples, I came across a model that has 8 different notifications that get sent out based on state changes. They all require unique configurations, which makes the model bulky just in the `notify_on` lines.

Therefore, I'm going to explore having an external file load these configurations when the server is initialized.

**Comment by digerata** [comment]
Something like an initializer would be the way to go, right?

**Comment by seancdavis** [comment]
Yes, and we do have an initializer, but this particular case felt like it called for a nice YAML config file.

Check out [this file](https://github.com/digerata/NotifyOn/blob/overhaul/lib/generators/templates/notify_on.rb). It is the initializer template that gets placed into your project when you run the install generator (see [here](https://github.com/digerata/NotifyOn/blob/overhaul/README.md#getting-started) for more info).

The initializer is loaded into an instance of [`NotifyOn::Configuration`](https://github.com/digerata/NotifyOn/blob/overhaul/lib/notify_on/configuration.rb), which provides a way to customize some of our defaults.

However, in this case, I wanted the notifications themselves to sit separate from the initializer and default settings. [This](https://github.com/digerata/NotifyOn/blob/overhaul/lib/generators/templates/notifications.yml) is the default template that gets placed to `config/notifications.yml` when you run the install generator. It can be used to add notifications one time, in bulk, or it can be ignored and notifications can be added to each model that should trigger them. It is then [these lines](https://github.com/digerata/NotifyOn/blob/overhaul/lib/notify_on/engine.rb#L13-L15) that calls [`NotifyOn::BulkConfig`](https://github.com/digerata/NotifyOn/blob/overhaul/lib/notify_on/bulk_config.rb), which looks at this YAML config file and essentially mimics calls to `notify_on` given the settings in the YAML file.

**Comment by digerata** [comment]
Real nice.
