### ISSUE TITLE
Enable TravisCI

### ISSUE THREAD

**Issue by seancdavis** [digerata/notify#21]
I _should_ be able to take it the rest of the way after it's connected. Just need it flipped on. I _believe_ that will happen on [this page](https://travis-ci.org/profile/digerata) for you.

**Comment by digerata** [comment]
Sorry about the delay. Should be all set. https://travis-ci.org/digerata/NotifyOn

**Comment by seancdavis** [comment]
Thank you! Appears to be working, but I'll let you know if I run into anything I can't fix without access.

**Comment by seancdavis** [comment]
@digerata: Doesn't seem like it's hooked up any more—builds are not being triggered.

**Comment by digerata** [comment]
Strange. I deactivated and reactivated it in travis... Let me see if it picks up a new build from me.

**Comment by digerata** [comment]
Okay, it picked up a new branch and started a build. Let me know how it works for you.

**Comment by seancdavis** [comment]
That did the trick. Thanks, @digerata!

I'm guessing it had something to do with moving the repository. We should be good now.
