### ISSUE TITLE
to: fails if passing an ActiveRecord_Associations_CollectionProxy

### ISSUE THREAD

**Issue by digerata** [digerata/notify#27]
I'm using the following:

    notify_on :create, { to: :project_users, email: 'new_build' }

    def project_users
        project.users
    end

The class has a dependent object project with a `has_many :users` relation. The code throws an exception:

    undefined method `primary_key' for User::ActiveRecord_Associations_CollectionProxy:Class

If I instead use: `project.users.to_a`, everything works fine.

**Comment by seancdavis** [comment]
Without testing it, I'm guessing [this line](https://github.com/BrilliantChemistry/NotifyOn/blob/overhaul/lib/notify_on/creator.rb#L24) is the culprit:

```ruby
(to.is_a?(Array) ? to : [to]).each do |recipient|
```

Because `to` is not an array, so it's trying to use the collection as an object.

I bet writing that line like this would do the trick:

```ruby
(to.respond_to?(:each) ? to : [to]).each do |recipient|
```

**Comment by digerata** [comment]
Thanks, that was it. I've got a branch of any other fixes we find.
