### ISSUE TITLE
Named Route Helpers are not present in notification mail views

### ISSUE THREAD

**Issue by digerata** [digerata/notify#28]
In model: `notify_on :create, { to: :project_users, email: { template: 'new_alert' } }`

Created: `views/notifications/new_alert.html.erb`

An email is sent based on the contents of new_alert.html.erb. However, if I add a named route helper, such as: `<%= root_url %>` or `<%= projects_url %>' I get an exception rendering the view:

    undefined method `projects_url' for #<#<Class:0x007fb73b74eb78>:0x007fb7432fa470>

**Comment by seancdavis** [comment]
Not a comprehensive solution, but should fix your issue.

**Comment by digerata** [comment]
Awesome, thanks!
